# Generated by Django 2.2.1 on 2019-05-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='DictValue',
        ),
    ]
