# Generated by Django 2.2.1 on 2019-05-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_remove_dict_dictvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ShopNotice',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
