# Generated by Django 2.2.1 on 2019-05-16 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_auto_20190515_1335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pageconfig',
            table='myapp_pageconfig',
        ),
    ]
