# Generated by Django 2.2.1 on 2019-05-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_auto_20190528_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestreceaddress',
            name='GReceCityID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guestreceaddress',
            name='GReceDistrictID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guestreceaddress',
            name='GReceProvinceID',
            field=models.IntegerField(null=True),
        ),
    ]
