# Generated by Django 2.2.1 on 2019-05-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_shop_shopnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticleTypeName',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
