# Generated by Django 2.2.1 on 2019-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_good_goodhotsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='GoodMainUrl',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
