# Generated by Django 2.2.1 on 2019-05-27 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_auto_20190524_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_GuestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelapp.Guest'),
        ),
    ]
