# Generated by Django 2.2.1 on 2019-06-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0005_good_goodmainurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='dict',
            name='DictRemark',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
